ecommercepractie/ecommercepractie/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from myapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.home,name='home'),
    url(r'^category/$',views.CategoryView.as_view(),name='category'),
    path('category_product_list/<slug:slug>/',views.CategoryProductList.as_view(),name='category_product_list'),
    path('product_detail/<slug:slug>/',views.ProductDetail.as_view(),name='product_detail'),
    path('cart_add/<int:pro_id>/',views.Cart_Add.as_view(),name='cart_add'),
    path('mycart/',views.mycart,name='mycart'),
    path('managecart/<int:cp_id>/',views.ManageCartView.as_view(),name='managecart'),
    path('emptycart/',views.EmptyCartView.as_view(),name="emptycart"),
    path('checkout/',views.CheckOutView.as_view(),name='checkout'),
    url(r'^search/$',views.search,name='search'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommercepractie/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    joined_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="cat_pics",blank=True)
    slug=models.SlugField(unique=True,blank=True)
    def __str__(self):
        return self.title

class Product(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="post_pics")
    mark_price=models.PositiveIntegerField()
    sell_price=models.PositiveIntegerField()
    description=models.TextField()
    warranty=models.CharField(max_length=100)
    return_policy=models.CharField(max_length=100)
    viewcount=models.PositiveIntegerField()

    def __str__(self):
        return self.title
class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='post_pics')

    def __str__(self):
        return self.product.title

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total=models.PositiveIntegerField()
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart "+str(self.id)

class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.PositiveIntegerField()
    quantity=models.PositiveIntegerField()
    subtotal=models.PositiveIntegerField()

    def __str__(self):
        return "Cart: "+str(self.cart.id)+str(self.id)

ORDER_STATUS=(('order received','Order Received'),
              ('order processing','Order Processing'),
              ('on the way','On The Way'),
              ('order completed','Order Completed'),

)

class Order(models.Model):
    cart=models.OneToOneField(Cart,on_delete=models.CASCADE)
    order_by=models.CharField(max_length=264,blank=True)
    shipping_address=models.CharField(max_length=100)
    mobile=models.CharField(max_length=100)
    email=models.EmailField()
    subtotal=models.PositiveIntegerField()
    discount=models.PositiveIntegerField()
    total=models.PositiveIntegerField()
    order_status=models.CharField(max_length=264,choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order "+str(self.id)

ecommercepractie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>ecommerceproject</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
<div class="container">
<h1 class="my-2 text-white  pb-1"><img src="{% static 'images/iphone.jpg' %}" height=50px>MobileWorld</h1>
<form class="d-flex" action='/search'>
     <input name='q' class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
     <button class="btn btn-success" type="submit">Search</button>
   </form>
<ul class="navbar-nav ml-auto">
<li class="mx-2"><a class="text-white" href="{% url 'home' %}">Home</a></li>
<li class="mx-2"><a class="text-white" href="{% url 'category' %}">Categories</a></li>
<li class="mx-2"><a class="text-white" href="{% url 'mycart' %}">Cart</a></li>

</ul>
</div>
</nav>
{% block body_block %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container-expand-lg bg-danger">
<div class="row">
<div class="colo-12 col-md">
<h3><a class="text-white mx-3" style="text-decoration:none;" href="#">MobileWorld</a></h5>

</div>
<div class="col-6 col-md">
<h5>Features</h5>
<ul class="list-unstyled text-small">
<li><a class="text-white">Cool Stuff</a></li>
<li><a class="text-white">Random Features</a></li>
<li><a class="text-white">Team Features</a></li>
<li><a class="text-white">Stuff For Developers</a></li>
<li><a class="text-white">Last Time</a></li>
</ul>
</div>
<div class="col-6 col-md">
<h5>Common Things</h5>
<ul class="list-unstyled text-small">
<li><a class="text-white">Cool Stuff</a></li>
<li><a class="text-white">Random Features</a></li>
<li><a class="text-white">Team Features</a></li>
<li><a class="text-white">Stuff For Developers</a></li>
<li><a class="text-white">Last Time</a></li>
</ul>
</div>
<div class="col-6 col-md">
<h5>Genera Stores</h5>
<ul class="list-unstyled text-small">
<li><a class="text-white">Cool Stuff</a></li>
<li><a class="text-white">Random Features</a></li>
<li><a class="text-white">Team Features</a></li>
<li><a class="text-white">Stuff For Developers</a></li>
<li><a class="text-white">Last Time</a></li>
</ul>
</div>
<h6 class="text-white my-2 mx-3">&copy;AllRights Reserved to Mr.NarednraBabu</h6>
</div>
</footer>

</body>
</html>

ecommercepractie/templates/cart_add.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Add to Cart SuccessFully</h1>
{% endblock %}

ecommercepractie/templates/cat_list.html
{% extends 'base.html' %}
{% block body_block %}
<main class="my-4 container">
<h3 class="my-4 pb-1 text-center">Categories</h3>
<div class="row">
{% for c in cat_list %}
<div class="col-md-3 mb-4">
<div class="card shadow">
<a href="{% url 'category_product_list' c.slug %}" class="my-2"><img src="{{c.image.url}}" alt="post_list.title" height=150px></a>
</div>
<div class="card-body">
<a href="{% url 'category_product_list' c.slug %}">{{c.title}}</a>
</h6>
</div>
</div>
{% endfor %}
</div>
</main>
{% endblock %}

ecommercepractie/templates/cat_product_list.html
{% extends 'base.html' %}
{% block body_block %}
<main class="my-4 container">
<h3 class="my-4 pb-1 text-center">{{category.title}}</h3>
<div class="row">
{% for cat in category_product_list %}
<div class="col-md-3 mb-4">
<div class="card shadow">
<a href="{% url 'product_detail' cat.slug %}" class="my-2"><img src="{{cat.image.url}}" alt="cat.title" height=150px></a>
</div>
<div class="card-body">
<a href="{% url 'product_detail' cat.slug %}">{{cat.title}}</a>
<h6><strike><font color="red">Rs {{cat.mark_price}}</font></strike>&nbsp;<font color="green">Rs {{cat.sell_price}}</font>
</h6>
</div>
</div>
{% endfor %}
</div>
</main>
{% endblock %}

ecommercepractie/templates/checkout.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
<div class="row">
<div class="col-md-6">
  <a href="{% url 'mycart' %}" class="btn btn-secondary">Update</a>
  <table class="table">
  <thead>
  <tr>
    <th>S.no</th>
    <th>Product</th>
    <th>Image</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
    {% for cp in cart.cartproduct_set.all %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{cp.product.title}}</td>
    <td><img src="{{cp.product.image.url}}" height=40px></td>
    <td>{{cp.rate}}</td>
    <td>{{cp.quantity}}</td>
    <td>{{cp.subtotal}}</td>
  </tr>
  {% endfor %}
  <tr>
  <th colspan="5">Total</th>
  <th>{{cart.total}}</th>
  </tr>
  </tbody>
  </table>
</div>

<div class="col-md-4 offset-1">
<h3>Checkout</h3>
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-success">
</form>
</div>
</div>

</div>
{% endblock %}

ecommercepractie/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<main class="my-4 container">
<h3 class="my-4 pb-1 text-center">Our Products</h3>
<div class="row">
{% for p in product_list %}
<div class="col-md-3 mb-4">
<div class="card shadow">
<a href="{% url 'product_detail' p.slug %}" class="my-2"><img src="{{p.image.url}}" alt="post_list.title" height=150px></a>
</div>
<div class="card-body">
<a href="{% url 'product_detail' p.slug %}">{{p.title}}</a>
<h6><strike><font color="red">Rs {{p.mark_price}}</font></strike>&nbsp;<font color="green">Rs {{p.sell_price}}</font>
<a href="{% url 'cart_add' p.id %}" class="btn btn-success mt-3">AddToCart</a>
</h6>
</div>
</div>
{% endfor %}
</div>
<ul class="pagination">
{% if product_list.has_previous %}
<li class="page-item">
<a href="?page=1" class="page-link">First</a>
</li>
<li class="page-item">
<a href="?page={{product_list.previous_page_number}}" class="page-link">Previous</a>
</li>
{% endif %}
{% if product_list.has_next %}
<li class="page-item">
<a href="?page={{product_list.next_page_number}}" class="page-link">Next></a>
</li>
<li class="page-item">
<a href="?page={{product_list.paginator.num_pages}}" class="page-link">Last>></a>
</li>
{% endif %}
</ul>
</main>
{% endblock %}

ecommercepractie/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
<div class="row">
<div class="col-md-6 mx-auto">
<h3>Login Form</h3>
<form method="POST" action="">
{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-primary" value="Login">
</form>
{% if error %}
{{error}}
{% endif %}
</div>
</div>
</div>
{% endblock %}

ecommercepractie/templates/mycart.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
<h3 class="my-4 pb-1">Items in my cart</h3>
<div class="row">
<div class="col-md-12 mb-4">
<table class="table">
<thead>
<tr>
  <th>S.no</th>
  <th>Product</th>
  <th>Image</th>
  <th>Price</th>
  <th>Quantity</th>
  <th>Subtotal</th>
  <th>Action</th>
</tr>
</thead>
<tbody>
  <tr>
    {% for cp in cart.cartproduct_set.all %}
    <td>{{forloop.counter}}</td>
    <td>{{cp.product.title}}</td>
    <td><img src="{{cp.product.image.url}}" height=40px></td>
    <td>{{cp.rate}}</td>
    <td>{{cp.quantity}}</td>
    <td>{{cp.subtotal}}</td>

    <td><a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary"><i class="fa fa-plus"></i></a>
    <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger"><i class="fa fa-remove"></i></a>
    <a href="{% url 'managecart' cp.id %}?action=dec" class="btn btn-warning"><i class="fa fa-minus"></i></a></td>
  </tr>


  {% endfor %}
  <tr>
  <th colspan="5">Total</th>
  <th>{{cart.total}}</th>
  {% if cart.cartproduct_set.all %}
  <th><a href="{% url 'emptycart' %}" class="btn btn-outline-primary">EmptyCart</a></th>
  {% endif %}
  </tr>
  <tr>
  <th><a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a></th>
  </tr>

</tbody>
</table>
</div>
</div>
</div>
{% endblock %}

ecommercepractie/templates/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="my-4 container">
<h3 class="my-4 pb-1 text-center">{{product.title}}</h3>
<div class="row">
<div class="col-md-6">
<h3 class="mt-2" align="center">{{product.title}}</h3>
<div class="card shadow"><img src="{{product.image.url}}" alt="{{product.title}}" height=300px></div>
<div class="row">
{% for pi in product.productimage_set.all %}
<div class="col-md-4">
<div class="card shadow mt-2"><img src="{{pi.image.url}}" class="image-fluid" height=200px style="object-fit:contain;"> </div>
</div>
{% endfor %}
</div>
<h4 class="text-center">Price:<strike><font color="red">RS{{product.mark_price}}</font></strike>&nbsp;<font color="green">Rs {{product.sell_price}}</font></h4>
</div>
<div class="col-md-6">
<div class="card-header"><font color="brown">{{product.title}}</font> Viewed:{{product.viewcount}}</div>
<div class="card-header">Category:{{product.category.title}}</div>
<div class="card-header">Warranty:{{product.warranty}}</div>
<div class="card-header">Return Policy:{{product.return_policy}}</div>
<a href="{% url 'cart_add' product.id %}" class="btn btn-success mt-3">AddToCart</a>
</div>
</div>
<div class="row">
<div class="col-md-12">
<h5>Description:</h5>
<p>{{product.description}}</p>
</div>

<div class="row">
<h3>Related Products</h3>
{% for p in related %}
<div class="col-md-3 mb-4">
<div class="card shadow">
<a href="{% url 'product_detail' p.slug %}" class="my-2"><img src="{{p.image.url}}" alt="post_list.title" height=150px></a>
</div>
<div class="card-body">
<a href="{% url 'product_detail' p.slug %}">{{p.title}}</a>
<h6><strike><font color="red">Rs {{p.mark_price}}</font></strike>&nbsp;<font color="green">Rs {{p.sell_price}}</font>
</h6>
</div>
</div>
{% endfor %}
</div>

</div>
</div>
{% endblock %}

ecommercepractie/templates/register.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
<div class="row">
<div class="col-md-6 mx-auto">
<h3>Customer Registration Form</h3>
<form method="POST" action="">
{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-primary" value="Register">
</form>
</div>
</div>
</div>
{% endblock %}

ecommercepractie/templates/search.html
{% extends 'base.html' %}
{% block body_block %}
<main class="my-4 container">
<h3 class="my-4 pb-1 text-center">Search Results for {{request.GET.q}}</h3>
<div class="row">
{% for p in product_list %}
<div class="col-md-3 mb-4">
<div class="card shadow">
<a href="{% url 'product_detail' p.slug %}" class="my-2"><img src="{{p.image.url}}" alt="post_list.title" height=150px></a>
</div>
<div class="card-body">
<a href="{% url 'product_detail' p.slug %}">{{p.title}}</a>
<h6><strike><font color="red">Rs {{p.mark_price}}</font></strike>&nbsp;<font color="green">Rs {{p.sell_price}}</font>
<a href="{% url 'cart_add' p.id %}" class="btn btn-success mt-3">AddToCart</a>
</h6>
</div>
</div>
{% endfor %}
</div>
</main>
{% endblock %}